   
prokatauto_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }
    condition: "context.getMethod() in ['GET', 'HEAD']"
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation