<?php
$outstr='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';
$outstr.='<html xmlns="http://www.w3.org/1999/xhtml" lang="ru" xml:lang="ru">';
$outstr.='<head>';
$outstr.='<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>';
$outstr.='<title>Контакты.</title>';
$outstr.='<link href="style.css" rel="stylesheet" type="text/css" />';
$outstr.='<meta name="Keywords" content="Контакты,Прокат легковых автомобилей,прокат без залога,прокат без водителя,прокат авто без залога,прокат авто без водителя,Адрес,Электронная почта" />';
$outstr.='<meta name="robots" content="index,follow" />';
$outstr.='<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.2.min.js"></script>';
$outstr.='<script type="text/javascript" src="w_load.js" async></script>';
$outstr.='    <!-- Bootstrap core CSS -->';
$outstr.='    <link href="bootstrap/docs/dist/css/bootstrap.min.css" rel="stylesheet" />';
$outstr.='    <!-- Bootstrap theme -->';
$outstr.='    <link href="bootstrap/docs/dist/css/bootstrap-theme.min.css" rel="stylesheet" />';
$outstr.='    <!-- Custom styles for this template -->';
$outstr.='    <link href="bootstrap/theme.css" rel="stylesheet" />';
$outstr.='    <!-- Just for debugging purposes. Don\'t actually copy these 2 lines! -->';
$outstr.='    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->';
$outstr.='    <script type="text/javascript" src="bootstrap/docs/assets/js/ie-emulation-modes-warning.js"></script>';
$outstr.='    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->';
$outstr.='    <script type="text/javascript" src="bootstrap/docs/assets/js/ie10-viewport-bug-workaround.js"></script>';
$outstr.='    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->';
$outstr.='    <!--[if lt IE 9]>';
$outstr.='      <script type="text/javascript" src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>';
$outstr.='      <script type="text/javascript" src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>';
$outstr.='    <![endif]-->';
$outstr.='</head>';
$outstr.='<body id="body_container" style="position: absolute; width: 1160px; height: 800px;visibility:hidden;">'; //onload="javascript:Dimension();"
$outstr.='<script type="text/javascript">';
$outstr.='(function(i,s,o,g,r,a,m){';
$outstr.='	i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){';
$outstr.='		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),';
$outstr.='		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)';
$outstr.='})(window,document,"script","//www.google-analytics.com/analytics.js","ga");';
$outstr.='ga("create", "UA-43061315-1", "comuf.com");';
$outstr.='ga("send", "pageview");';
$outstr.='</script>';
$outstr.='<!-- Yandex.Metrika counter -->';
$outstr.='<script type="text/javascript">';
$outstr.='(function (d, w, c) {';
$outstr.='	(w[c] = w[c] || []).push(function() {';
$outstr.='		try {';
$outstr.='			w.yaCounter22020040 = new Ya.Metrika({';
$outstr.='				id:22020040,';
$outstr.='				clickmap:true,';
$outstr.='				trackLinks:true,';
$outstr.='				accurateTrackBounce:true});';
$outstr.='		} catch(e) {';
$outstr.='		}';
$outstr.='	});';
$outstr.='	var n = d.getElementsByTagName("script")[0],';
$outstr.='	s = d.createElement("script"),';
$outstr.='	f = function () {';
$outstr.='		n.parentNode.insertBefore(s, n);';
$outstr.='	};';
$outstr.='	s.type = "text/javascript";';
$outstr.='	s.async = true;';
$outstr.='	s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";';
$outstr.='	if (w.opera == "[object Opera]") {';
$outstr.='		d.addEventListener("DOMContentLoaded", f, false);';
$outstr.='	} else { f();';
$outstr.='	}';
$outstr.='})(document, window, "yandex_metrika_callbacks");';
$outstr.='</script>';
$outstr.='<noscript><div><img src="//mc.yandex.ru/watch/22020040" style="position:absolute; left:-9999px;" alt="" /></div></noscript>';
$outstr.='<!-- /Yandex.Metrika counter -->';
$outstr.='<script type="text/javascript">';
$outstr.='function Dimension ()';
$outstr.='{';
$outstr.='	var Width = (window.screen.width);';
$outstr.='	var Height = (window.screen.height);';
$outstr.='	if (Width < 1160) {';
$outstr.='		document.getElementById("container_cars").style.left="0px";';
$outstr.='	} else if (Width >= 1160) {';
$outstr.='		var left_size=Math.round((Width-1160)/2);';
$outstr.='		document.getElementById("container_cars").style.left=String(left_size)+"px";';
$outstr.='	}';
$outstr.='}';
$outstr.='</script>';
$outstr.='<div class="container1" id="container_contact" style="position:relative; left:0px; top:0px; width:1160px; height:800px; z-index:0;">';
$outstr.='<div id="h1_level1" class="h1" style="position:relative;display:block; left:0px; top:0px; width:1160px; height:40px; z-index:0;border-radius: 3px;border: 1px solid #000;overflow: hidden;">';
$outstr.='<h1 style="position:relative;left:0px; top:0px; width:1160px; height:40px; z-index:0; color:white;margin:0 0 0 0;">Контактная информация.</h1>';
$outstr.='</div>';
$outstr.='<a href="http://autovarendu.biz/"><button class="btn btn-lg btn-primary btn-block" name="_BakToMain" value="На главную">На главную</button></a>';
$outstr.='<div class="content_level1" style="position:relative;display:block; left:0px; top:20px; width:100%; height:656px;z-index:0;border-radius: 3px;border: 1px solid #000;overflow: hidden;">';
$outstr.='<div id="address_info_level1" class="ul.nav" style="position:relative; left:2%; top:2%; width:1024px; height:700px">';
$outstr.='<p>';
$outstr.='<div itemscope itemtype="http://schema.org/Organization">';
$outstr.='<span itemprop="name">Прокат автомобилей ИП Красавин Д.В.</span>';
$outstr.='<br />';
$outstr.='Время работы проката с 9:00 до 21:00.<br />';
$outstr.='Без выходных и перерывов.<br />';
$outstr.='<br />';
$outstr.='Адрес:';
$outstr.='<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">';
$outstr.='	<span itemprop="streetAddress">Довженко, 8/1</span>';
$outstr.='    <span itemprop="postalCode"> 119590</span>';
$outstr.='    <span itemprop="addressLocality">Москва</span>,';
$outstr.='  </div>';
$outstr.='<br />';
$outstr.='Телефон:<span itemprop="telephone">+7 916 141-21-80</span>,';
$outstr.='<br />';
$outstr.='  Факс:<span itemprop="faxNumber">+7 916 141-21-80</span>,';
$outstr.='<br/>';
$outstr.='  Электронная почта: <span itemprop="email">krasavin.prokat@gmail.com</span>';
$outstr.='</div>';
$outstr.='<br/>';
$outstr.='</p>';
$outstr.='<!-- Этот блок кода нужно вставить в ту часть страницы, где вы хотите разместить карту  (начало) -->';
$outstr.='<script src="http://api-maps.yandex.ru/1.1/?key=AObY9VMBAAAAn24AFQIAR3FLuG9EG--N9fEZzLBUBXacuHYAAAAAAAAAAAD2MWnll7x6F2CTdzVUYSBerzkBCA==&modules=pmap&wizard=constructor" type="text/javascript"></script>';
$outstr.='<script type="text/javascript">';
$outstr.='    YMaps.jQuery(window).load(function () {';
$outstr.='        var map = new YMaps.Map(YMaps.jQuery("#YMapsID-4027")[0]);';
$outstr.='        map.setCenter(new YMaps.GeoPoint(37.50982,55.722967), 16, YMaps.MapType.MAP);';
$outstr.='        map.addControl(new YMaps.Zoom());';
$outstr.='        map.addControl(new YMaps.ToolBar());';
$outstr.='        YMaps.MapType.PMAP.getName = function () { return "Народная"; };';
$outstr.='        map.addControl(new YMaps.TypeControl([';
$outstr.='            YMaps.MapType.MAP,';
$outstr.='            YMaps.MapType.SATELLITE,';
$outstr.='            YMaps.MapType.HYBRID,';
$outstr.='            YMaps.MapType.PMAP';
$outstr.='        ], [0, 1, 2, 3]));';
$outstr.='        YMaps.Styles.add("constructor#pmlbmPlacemark", {';
$outstr.='            iconStyle : {';
$outstr.='                href : "http://api-maps.yandex.ru/i/0.3/placemarks/pmlbm.png",';
$outstr.='                size : new YMaps.Point(28,29),';
$outstr.='                offset: new YMaps.Point(-8,-27)';
$outstr.='            }';
$outstr.='        });';
$outstr.='        YMaps.Styles.add("constructor#FF3732c85Polyline", {';
$outstr.='            lineStyle : {';
$outstr.='                strokeColor : "FF3732c8",';
$outstr.='                strokeWidth : 5';
$outstr.='            }';
$outstr.='        });';
$outstr.='       map.addOverlay(createObject("Placemark", new YMaps.GeoPoint(37.510892,55.722074), "constructor#pmlbmPlacemark", "ИП Красавин Д.В.<br/>Компьютерный сервис. Прокат автомобилей"));';
$outstr.='       map.addOverlay(createObject("Polyline", [new YMaps.GeoPoint(37.566836,55.744043),new YMaps.GeoPoint(37.568703,55.745035),new YMaps.GeoPoint(37.571536,55.745023),new YMaps.GeoPoint(37.571922,55.744757),new YMaps.GeoPoint(37.569712,55.741985),new YMaps.GeoPoint(37.566879,55.739225),new YMaps.GeoPoint(37.56424,55.736937),new YMaps.GeoPoint(37.56115,55.735061),new YMaps.GeoPoint(37.548018,55.729266),new YMaps.GeoPoint(37.546688,55.728818),new YMaps.GeoPoint(37.544778,55.728516),new YMaps.GeoPoint(37.541066,55.728213),new YMaps.GeoPoint(37.537954,55.727692),new YMaps.GeoPoint(37.534865,55.726505),new YMaps.GeoPoint(37.52115,55.718863),new YMaps.GeoPoint(37.520227,55.718851),new YMaps.GeoPoint(37.514949,55.721748),new YMaps.GeoPoint(37.517116,55.722969),new YMaps.GeoPoint(37.516408,55.723334),new YMaps.GeoPoint(37.515164,55.722728),new YMaps.GeoPoint(37.514863,55.723116),new YMaps.GeoPoint(37.514134,55.723455),new YMaps.GeoPoint(37.513104,55.723528),new YMaps.GeoPoint(37.512321,55.723334),new YMaps.GeoPoint(37.511966,55.723031),new YMaps.GeoPoint(37.511816,55.722571),new YMaps.GeoPoint(37.511945,55.722256),new YMaps.GeoPoint(37.51143,55.722062)], "constructor#FF3732c85Polyline", ""));';
$outstr.='        function createObject (type, point, style, description) {';
$outstr.='            var allowObjects = ["Placemark", "Polyline", "Polygon"],';
$outstr.='                index = YMaps.jQuery.inArray( type, allowObjects),';
$outstr.='                constructor = allowObjects[(index == -1) ? 0 : index];';
$outstr.='                description = description || "";';
$outstr.='            var object = new YMaps[constructor](point, {style: style, hasBalloon : !!description});';
$outstr.='            object.description = description;';
$outstr.='            return object;';
$outstr.='        }';
$outstr.='    });';
$outstr.='</script>';
$outstr.='<div id="YMapsID-4027" style="width:450px;height:350px"></div>';
$outstr.='<div style="width:450px;text-align:right;font-family:Arial"><a href="http://api.yandex.ru/maps/tools/constructor/" style="color:#1A3DC1">Создано с помощью инструментов Яндекс.Карт</a></div>';
$outstr.='<!-- Этот блок кода нужно вставить в ту часть страницы, где вы хотите разместить карту (конец) -->';
$outstr.='</div>';
$outstr.='</div>';
$outstr.='<div id="copyright_level1" class="ul.nav" style="position:relative; left: 40%; top:0px; width:200px; height:20px;font-size:13px;">';
$outstr.='<p class="a"> ИП Красавин Д.В. 2011-2015</p>';
$outstr.='</div>';
$outstr.='</div>';
$outstr.='</body>';
$outstr.='</html>';
echo $outstr;
?>