<?php
include_once "document_reader_class.php";
ini_set('display_errors', true);
$outstr='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';
$outstr.='<html xmlns="http://www.w3.org/1999/xhtml" lang="ru" xml:lang="ru">';
$outstr.='<head>';
$outstr.='<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>';
$outstr.='<meta name="Keywords" content="Аренда авто, аренда автомобиля, аренда автомобилей, аренда автомобилей без залога, аренда автомобиля без водителя, аренда автомобиля с водителем, аренда авто без залога, аренда авто без водителя, аренда авто с водителем, аренда skoda,аренда bmw,аренда ваз, новости рынка аренды автомобилей" />';
$outstr.='<meta name="robots" content="index,follow" />';
$outstr.='<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.2.min.js"></script>';
$outstr.='<script type="text/javascript" src="w_load.js" async></script>';
$outstr.='    <!-- Bootstrap core CSS -->';
$outstr.='    <link href="bootstrap/docs/dist/css/bootstrap.min.css" rel="stylesheet">';
$outstr.='    <!-- Bootstrap theme -->';
$outstr.='    <link href="bootstrap/docs/dist/css/bootstrap-theme.min.css" rel="stylesheet">';
$outstr.='    <!-- Custom styles for this template -->';
$outstr.='    <link href="bootstrap/theme.css" rel="stylesheet">';
$outstr.='    <!-- Just for debugging purposes. Don\'t actually copy these 2 lines! -->';
$outstr.='    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->';
$outstr.='    <script src="bootstrap/docs/assets/js/ie-emulation-modes-warning.js"></script>';
$outstr.='    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->';
$outstr.='    <script src="bootstrap/docs/assets/js/ie10-viewport-bug-workaround.js"></script>';
$outstr.='    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->';
$outstr.='    <!--[if lt IE 9]>';
$outstr.='      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>';
$outstr.='      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>';
$outstr.='    <![endif]-->';
$outstr.='<link href="style.css" type="text/css" rel="stylesheet"></link>';
$outstr.='<title>Новости-autovarendu.ru</title>';
//$outstr.='<script src="http://code.jquery.com/jquery-1.9.1.js"></script>';
$outstr.='</head>';
$outstr.='<body id="body_container" style="position: absolute; width:100%;height:100%;max-width:100%;max-height:100%;">'; //onload="javascript:Dimension();"
$outstr.='<script type="text/javascript">';
$outstr.='function Dimension ()';
$outstr.='{';
$outstr.='	var Width = (window.screen.width);';
$outstr.='	var Height = (window.screen.height);';
$outstr.='	if (Width < 1160) {';
$outstr.='		document.getElementById("container_news").style.left="0px";';
$outstr.='	} else if (Width >= 1160) {';
$outstr.='		var left_size=Math.round((Width-1160)/2);';
$outstr.='		document.getElementById("container_news").style.left=String(left_size)+"px";';
$outstr.='	}';
$outstr.='}';
$outstr.='</script>';
$outstr.='<div class="container1 container-fluid" id="container_news">';//style="position:relative; left:0px; top:0px; width:1160px; height:800px; z-index:0;margin-top:7%;"
$outstr.='<div class="h1" id="h1_level" style="position:relative;display:block; left:0px; top:0px; width:1160px; height:40px; z-index:0;border-radius: 3px;border: 1px solid #000;overflow: hidden;">';
$outstr.='<h1 style="position:relative;left:0px; top:0px; width:1160px; height:40px; z-index:0; color:white;margin:0 0 0 0;">Новости</h1>';
$outstr.='</div>';
$outstr.='<a href="http://autovarendu.biz/"><button class="btn btn-lg btn-primary btn-block" name="_BakToMain" value="На главную">На главную</button></a>';
$outstr.='<div class="content_level1" id="content_level" style="position:relative;display:block; left:0px; top:20px; width:100%; height:656px;z-index:0;border-radius: 3px;border: 1px solid #000;overflow: hidden;">';
$outstr.='<div class="list_of_helpitems" id="list_of_helpitems_div4" style="position:relative; margin:auto; top:2%; width:800px;height:50px;overflow: hidden;z-index:0;">';
$outstr.='<h2 style="font-size:12px;position:relative;">10-02-2015 Опубликованы первые фотографии серийной Lada Vesta</h2>';
$outstr.='<span style="font-size:12px;position:relative;">';
$outstr.='<pre style="font-size:12px;position:relative;top:6px;">';
$mydocument_reader_class=new document_reader_class('newsinfo/news4.txt');
$outstr.=$mydocument_reader_class->get_file_data('newsinfo/news4.txt');
$outstr.='</pre>';
$outstr.='</span>';
$outstr.='</div>';
$outstr.='<div class="list_of_helpitems" id="list_of_helpitems_div3" style="position:relative; margin:auto; top:4%; width:800px;height:50px;overflow: hidden;z-index:0;">';
$outstr.='<h2 style="font-size:12px;position:relative;">25-08-2014 Названы самые дешевые и самые дорогие для автотуристов страны Европы.</h2>';
$outstr.='<span style="font-size:12px;position:relative;">';
$outstr.='<pre style="font-size:12px;position:relative;top:6px;">';
$mydocument_reader_class=new document_reader_class('newsinfo/news3.txt');
$outstr.=$mydocument_reader_class->get_file_data('newsinfo/news3.txt');
$outstr.='</pre>';
$outstr.='</span>';
$outstr.='</div>';
$outstr.='<div class="list_of_helpitems" id="list_of_helpitems_div2" style="position:relative; margin:auto; top:6%; width:800px;height:50px;overflow: hidden;z-index:0;">';
$outstr.='<h2 style="font-size:12px;">25-07-2014 Hyundai Motor объявляет о результатах продаж за первое полугодие 2014 года</h2>';
$outstr.='<span style="font-size:12px;position:relative;">';
$outstr.='<pre style="font-size:12px;position:relative;top:6px;">';
$mydocument_reader_class=new document_reader_class('newsinfo/news2.txt');
$outstr.=$mydocument_reader_class->get_file_data('newsinfo/news2.txt');
$outstr.='</pre>';
$outstr.='</span>';
$outstr.='</div>';
$outstr.='<div class="list_of_helpitems" id="list_of_helpitems_div1" style="position:relative; margin:auto; top:8%; width:800px;height:50px;overflow: hidden;z-index:0;">';
$outstr.='<h2 style="font-size:12px;position:relative;">23-07-2013 13:10 Власти подмосковья возьмутся за утилизацию автомобилей.</h2>';
$outstr.='<span style="font-size:12px;position:relative;top:6px;">';
$outstr.='<pre>';
$mydocument_reader_class=new document_reader_class('newsinfo/news1.txt');
$outstr.=$mydocument_reader_class->get_file_data('newsinfo/news1.txt');
$outstr.='</pre>';
$outstr.='</span>';
$outstr.='</div>';
$outstr.='</div>';
$outstr.='<script type="text/javascript">';
$outstr.='$(window).load(function() {';
$outstr.='$("#list_of_helpitems_div").height()=\'50px\';';
$outstr.='});';
$outstr.='$(document).ready(function() {';
$outstr.='$("#list_of_helpitems_div1,#list_of_helpitems_div2,#list_of_helpitems_div3,#list_of_helpitems_div4").hover(';
$outstr.='function() {';
$outstr.='$(this).animate({';
$outstr.='height: "500px"';
$outstr.='}, "slow"';
$outstr.=');';
$outstr.='$(this).css(';
$outstr.='"overflow-y","scroll");';
$outstr.='},';
$outstr.='function() {';
$outstr.='$(this).animate({';
$outstr.='height: "50px"';
$outstr.='}, "slow"';
$outstr.=');';
$outstr.='$(this).css(';
$outstr.='"overflow","hidden");';
$outstr.='}';
$outstr.=');';
$outstr.='});';
$outstr.='</script>';
$outstr.='<div id="copyright_level1" class="ul" style="position:relative; left: 40%; top:0%; width:200px; height:20px;font-size:13px;">';
$outstr.='<p class="a"> ИП Красавин Д.В. 2011-2015</p>';
$outstr.='</div>';
$outstr.='</div>';
$outstr.='</body>';
$outstr.='</html>';
echo $outstr;
?>
